import { useState } from 'react'

import Head from 'next/head'

import AppBar from '@mui/material/AppBar';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';

import Container from '@mui/material/Container';

import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';

export default function Home() {
  // I want you to load the data in a stateful variable called quoteData
  const [quoteData, setQuoteData] = useState({
    quote: "Answer my questions",
    author: "Dan the wisdom man."
  })

  // when the user clicks the button
  const getRandomQuote = async () => {
    // since the endpoint is on the same domain
    // (localhost:3000 or whatever production you use)
    // we don't need to specify the path.

    // handle requests use a try catch
    try {
      // make the request
      const response = await fetch('/api/random_quote')
      const data = await response.json()
      // set the state
      setQuoteData(data)
    } catch (error) {
      // this error we're not handling but you should
      // display something to the user.
      console.log(error)
    }
  }
  // I want you to show it on the page.

  // you'll need to handle some type of loading case.

  return (
    <div>
      <Head>
        <title>We Love Quotes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>
      <AppBar position="relative">
        <Toolbar>
          <Typography variant="h6" color="inherit" noWrap>
            We Love Quotes
          </Typography>
        </Toolbar>
      </AppBar>
      <main>
        <Container maxWidth="sm">
          <Box
            sx={{
              bgcolor: 'background.paper',
              pt: 8,
              pb: 6,
            }}
          >
            <Typography variant="h5" align="center" color="text.primary" paragraph>
              {quoteData.quote}
            </Typography>
            <Typography
              component="h1"
              variant="h4"
              align="center"
              color="text.secondary"
              gutterBottom
            >
              {quoteData.author}
            </Typography>
            <Box
             display="flex"
             justifyContent="center"

            >
              <Button
                variant="contained"
                onClick={getRandomQuote}
              >
                Get New Quote
              </Button>
            </Box>
          </Box>
        </Container>
      </main>
    </div>
  )
}
